### ISSUE TITLE
Flipper FMT

### ISSUE THREAD

**Issue by RogueMaster** [xtruan/FlipBIP#2]
Hi, I'm very interested in your project and have added it to my firmware. I have made some format changes with text replacement and `./fbt format` in order to change the code to the flipper devices desired formatting (file names and folders with a _ instead of - amongst other changes). If you are interested in the changes, here they are: https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/de2ad7c762e29526185b5f503d407a8293efb6fe

I almost made it to ETHDenver, I was registered even. 😄 Hopefully, I make it next year! Hope it was a fun event!

**Comment by xtruan** [comment]
Legit! I actually use your firmware on my device, it's fantastic!!! I will pull in these changes when I get a chance!

I'm actively developing the functionality to persist the seed (securely) on the device so that the Flipper can be used as a cold wallet vs. just a wallet generator. I'll keep you posted.

ETHDenver was fun, I only decided to go last minute but it was definitely worth it.

**Comment by xtruan** [comment]
Fixed in `v0.0.4`!
